global:
  resolve_timeout: 5m

route:
  receiver: "default"
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: "default"
    # This means: just log alerts to Alertmanager’s web UI – no email/slack/etc

# (Optional) inhibition rules – suppress related alerts
inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'dev', 'instance']
