version: '3.7'

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: home-assistant
    restart: unless-stopped
    volumes:
      - homeassistant_config:/config
    environment:
      - TZ=America/Chicago  # Change this to your timezone
    ports:
      - "8123:8123"  # Web UI access
    network_mode: host
    privileged: true  # Required for some Home Assistant features

volumes:
  homeassistant_config:
    driver: local
